### ISSUE TITLE
No way to reset the timer?

### ISSUE THREAD

**Issue by martin-wiseweb** [husa/timer.js#12]
I thought that if I do timer.stop() it might reset the timer back to 0. But it does not.

Is this expected? If so, how can I reset the timer back to 0 seconds?

**Comment by husa** [comment]
@martin-wiseweb  `stop` should actually stop the timer. Have you found the solution to your problem?

**Comment by martin-wiseweb** [comment]
Yeah sorry I was not paying attention it works as intended!
