### ISSUE TITLE
When starting the timer again with different time it takes the initial value

### ISSUE THREAD

**Issue by feimosi** [husa/timer.js#8]
I've just discovered an unexpected behaviour. When you start the timer again, let's say for the second time, it uses the previous time length, e.g. always 5 seconds. Even when you stop it before doesn't help. The workaround is to create a new object each time.

**Comment by husa** [comment]
@feimosi thanks for reporting. Good catch.

**Comment by feimosi** [comment]
@husa You're welcome. Thanks for a quick fix.
